"""initial migration

Revision ID: 3239fa9deacd
Revises: 
Create Date: 2020-10-25 21:31:31.781887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3239fa9deacd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paysim_data2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paysim_data2',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('step', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('transtype', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('amount', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('nameOrig', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('oldbalanceOrg', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('newbalanceOrig', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('nameDest', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('oldbalanceDest', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('newbalanceDest', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('isFraud', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('isFlaggedFraud', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
